### ISSUE TITLE
Set Open & Close Positions for Blinds

### ISSUE THREAD

**Issue by bledsoe812** [arachnetech/homebridge-mqttthing#466]
I'm completing this project, but I want to use my existing Homebridge setup instead of Home Assistant.

https://github.com/thehookup/Motorized_MQTT_Blinds

The YAML for Home Assistant (that works great in HA) is as follows.
```
cover:
  - platform: mqtt
    name: "Blinds-5"
    command_topic: "Blinds-5/blindsCommand"
    set_position_topic: "Blinds-5/positionCommand"
    position_topic: "Blinds-5/positionState"
    state_topic: "Blinds-5/positionState"
    retain: true
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STOP"
    position_open: 0
    position_closed: 12
```

Trying to use the mqqtthing plugin to add the device using the following config.
```
{
            "type": "windowCovering",
            "name": "Blinds-5",
            "url": "mqtt://<IP-address>:1883",
            "username": "<user>",
            "password": "<pass>",
            "mqttOptions": {
                "keepalive": 60
            },
            "mqttPubOptions": {
                "retain": true
            },
            "logMqtt": true,
            "topics": {
                "getOnline": "Blinds-5/blindsCommand",
                "getCurrentHorizontalTiltAngle": "Blinds-5/positionState",
                "getCurrentPosition": "Blinds-5/positionState",
                "setHoldPosition": "Blinds-5/positionCommand",
                "getPositionState": "Blinds-5/positionState",
                "setTargetHorizontalTiltAngle": "Blinds-5/positionCommand",
                "getTargetPosition": "Blinds-5/positionState",
                "setTargetPosition": "Blinds-5/positionCommand"
            },
            "positionStateValues": [
                "DEC",
                "INC",
                "STOP"
            ],
            "accessory": "mqttthing"
        }
```
The blinds show up in HomeKit, and they are fully functional (open, close, percentage) all respond and rotate the motor.  The problem is Opening the blinds rotates the motor like 5 cycles.  I need to customize this (as seen in the HA YAML) to around 12 steps, instead of it currently doing around 60 steps.  Is this possible to change the open and close positions of the stepper motor?
